model:
  algorithm: SAMME.R
  base_estimator: null
  learning_rate: 1.0
  n_estimators: 50
  random_state: 42
model_class: AdaBoostClassifier
tfidf:
  analyzer: word
  binary: false
  decode_error: strict
  dtype: <class 'numpy.float64'>
  encoding: utf-8
  input: content
  lowercase: true
  max_df: 1.0
  max_features: 25000
  min_df: 1
  ngram_range: (1, 1)
  norm: l2
  preprocessor: null
  smooth_idf: true
  stop_words: null
  strip_accents: null
  sublinear_tf: false
  token_pattern: (?u)\b\w\w+\b
  tokenizer: null
  use_idf: true
  vocabulary: null
