model:
  alpha: 0.0001
  average: false
  class_weight: null
  early_stopping: false
  epsilon: 0.1
  eta0: 0.0
  fit_intercept: true
  l1_ratio: 0.15
  learning_rate: optimal
  loss: modified_huber
  max_iter: 1000
  n_iter_no_change: 5
  n_jobs: null
  penalty: l2
  power_t: 0.5
  random_state: 42
  shuffle: true
  tol: 0.001
  validation_fraction: 0.1
  verbose: 0
  warm_start: false
model_class: SGDClassifier
tfidf:
  analyzer: word
  binary: false
  decode_error: strict
  dtype: <class 'numpy.float64'>
  encoding: utf-8
  input: content
  lowercase: true
  max_df: 1.0
  max_features: 25000
  min_df: 1
  ngram_range: (1, 1)
  norm: l2
  preprocessor: null
  smooth_idf: true
  stop_words: null
  strip_accents: null
  sublinear_tf: false
  token_pattern: (?u)\b\w\w+\b
  tokenizer: null
  use_idf: true
  vocabulary: null
